# Generated by Django 2.0.13 on 2019-05-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alupostcomtracker',
            old_name='Alarms_Preventing_RET_Config',
            new_name='Is_Pre_Integration_site',
        ),
        migrations.RenameField(
            model_name='alupostcomtracker',
            old_name='IP_Route_or_IP_Address',
            new_name='OSS',
        ),
        migrations.RenameField(
            model_name='alupostcomtracker',
            old_name='LSM',
            new_name='Onshore_Eng_Name',
        ),
        migrations.RenameField(
            model_name='alupostcomtracker',
            old_name='Lock_Unlock_Verified_By',
            new_name='Post_E_Tilt_Values',
        ),
        migrations.RenameField(
            model_name='alupostcomtracker',
            old_name='Remarks',
            new_name='Post_Max_User_Count',
        ),
        migrations.RenameField(
            model_name='alupostcomtracker',
            old_name='Review_LATP_Complete',
            new_name='Pre_E_Tilt_Values',
        ),
        migrations.RenameField(
            model_name='alupostcomtracker',
            old_name='Verify_Status',
            new_name='Pre_Max_User_Count',
        ),
        migrations.RenameField(
            model_name='alupostcomtracker',
            old_name='Volte_MME_IP_Config',
            new_name='RSD_Air_Boss',
        ),
        migrations.RemoveField(
            model_name='alupostcomtracker',
            name='Activity',
        ),
        migrations.RemoveField(
            model_name='alupostcomtracker',
            name='Bandwidth_Checked_From_LSM',
        ),
        migrations.RemoveField(
            model_name='alupostcomtracker',
            name='E_Link_Status_of_BH0_for_CDU30',
        ),
        migrations.RemoveField(
            model_name='alupostcomtracker',
            name='Frequency_Earfcn_Checked_from_LSM_BSM',
        ),
        migrations.RemoveField(
            model_name='alupostcomtracker',
            name='MJ_Object_Marked',
        ),
        migrations.RemoveField(
            model_name='alupostcomtracker',
            name='Mode_of_Communication',
        ),
        migrations.RemoveField(
            model_name='alupostcomtracker',
            name='RET',
        ),
        migrations.AddField(
            model_name='alupostcomtracker',
            name='Bridge_No',
            field=models.CharField(blank=True, choices=[('Bridge-1', 'Bridge-1'), ('Bridge-2', 'Bridge-2'), ('Bridge-3', 'Bridge-3'), ('Bridge-4', 'Bridge-4'), ('Bridge-5', 'Bridge-5'), ('Bridge-6', 'Bridge-6'), ('Bridge-7', 'Bridge-7'), ('Bridge-8', 'Bridge-8'), ('Bridge-9', 'Bridge-9'), ('Bridge-10', 'Bridge-10'), ('Bridge-11', 'Bridge-11'), ('Bridge-12', 'Bridge-12'), ('Bridge-13', 'Bridge-13'), ('Bridge-14', 'Bridge-14'), ('Bridge-15', 'Bridge-15'), ('E-Mail', 'E-Mail')], max_length=255),
        ),
        migrations.AddField(
            model_name='alupostcomtracker',
            name='OEM',
            field=models.CharField(blank=True, choices=[('Airscale', 'Airscale'), ('ALU', 'ALU'), ('NSN', 'NSN')], max_length=255),
        ),
        migrations.AddField(
            model_name='alupostcomtracker',
            name='Revisit_Required',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='alupostcomtracker',
            name='Site_Activity_Type',
            field=models.CharField(blank=True, choices=[('Cabinet Swap', 'Cabinet Swap'), ('Change In SAMB', 'Change In SAMB'), ('Health Check', 'Health Check'), ('LAM Testing', 'LAM Testing'), ('LATP/FATP Testing', 'LATP/FATP Testing'), ('Mini M Decom Macro', 'Mini M Decom Macro'), ('New Integration', 'New Interation'), ('Relo Site', 'Relo Site'), ('Technology ADD', 'Technology ADD'), ('Troubleshooting', 'Troubleshooting')], max_length=255),
        ),
        migrations.AddField(
            model_name='alupostcomtracker',
            name='Volte_Market',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
