# Generated by Django 2.0.13 on 2019-05-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alu', '0003_auto_20190509_0136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alupostcomtracker',
            name='Type',
        ),
        migrations.RemoveField(
            model_name='alupostcomtracker',
            name='Volte_Market',
        ),
        migrations.AlterField(
            model_name='alupostcomtracker',
            name='Is_Pre_Integration_site',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255),
        ),
        migrations.AlterField(
            model_name='alupostcomtracker',
            name='Post_Reserve',
            field=models.CharField(blank=True, choices=[('Reserved', 'Reserved'), ('CP-INH', 'CP-INH'), ('Not Reserved', 'Not Reserved'), ('Grow', 'Grow'), ('Equiped', 'Equiped')], max_length=255),
        ),
        migrations.AlterField(
            model_name='alupostcomtracker',
            name='Pre_Reserve',
            field=models.CharField(blank=True, choices=[('Reserved', 'Reserved'), ('CP-INH', 'CP-INH'), ('Not Reserved', 'Not Reserved'), ('Grow', 'Grow'), ('Equiped', 'Equiped')], max_length=255),
        ),
        migrations.AlterField(
            model_name='alupostcomtracker',
            name='Revisit_Required',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255),
        ),
        migrations.AlterField(
            model_name='alupostcomtracker',
            name='Technology',
            field=models.CharField(choices=[('800 CDMA', '800 CDMA'), ('1900 CDMA', '1900 CDMA'), ('800 FDD', '800 FDD'), ('1900 FDD', '1900 FDD'), ('2.5 TDD', '2.5 TDD'), ('700 FDD', '700 FDD')], max_length=255),
        ),
    ]
