# Generated by Django 2.0.13 on 2019-05-14 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alu', '0006_auto_20190514_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='AluRsaTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cascade', models.CharField(default='', max_length=255)),
                ('Technology', models.CharField(choices=[('800 CDMA', '800 CDMA'), ('1900 CDMA', '1900 CDMA'), ('800 FDD', '800 FDD'), ('1900 FDD', '1900 FDD'), ('2.5 TDD', '2.5 TDD'), ('700 FDD', '700 FDD')], max_length=255)),
                ('Source', models.CharField(choices=[('Normal RSA', 'Normal RSA'), ('MIMO RSA', 'MIMO RSA'), ('Brenda OAC', 'Brenda OAC'), ('Brenda ATP', 'Brenda ATP'), ('Brenda RSA Only', 'Brenda RSA Only'), ('RSA Only', 'RSA Only'), ('Manual LATP', 'Manual LATP'), ('Spectrum clear', 'Spectrum Clear'), ('Mail RSA', 'Mail RSA')], max_length=255)),
                ('Sity_Type', models.CharField(choices=[('Monopole', 'Monopole'), ('Roof Top', 'Roof Top'), ('Substantial Services', 'Substantial Services'), ('Macro', 'Macro'), ('Swap – NV to NV', 'Swap – NV to NV'), ('Swap – Legacy to NV', 'Swap – Legacy to NV')], max_length=255)),
                ('OEM', models.CharField(blank=True, choices=[('Airscale', 'Airscale'), ('ALU', 'ALU'), ('NSN', 'NSN')], max_length=255)),
                ('Market', models.CharField(blank=True, choices=[('Kansas', 'Kansas'), ('Alaska', 'Alaska'), ('PR / VI', 'PR / VI'), ('DFW', 'DFW'), ('East Texas', 'East Texas'), ('Inland Northwest', 'Inland Northwest'), ('Albuquerque', 'Albuquerque'), ('Jacksonville', 'Jacksonville'), ('Nashville', 'Nashville'), ('West Texas', 'West Texas'), ('Washington DC', 'Washington DC'), ('East Iowa', 'East Iowa'), ('MT / WY', 'MT / WY'), ('South Carolina', 'South Carolina'), ('Riverside / San Bernardino', 'Riverside / San Bernardino'), ('East Kentucky', 'East Kentucky'), ('Alabama', 'Alabama'), ('West Kentucky', 'West Kentucky'), ('Dakotas', 'Dakotas'), ('Orlando', 'Orlando'), ('Central Iowa', 'Central Iowa'), ('Georgia', 'Georgia'), ('Missouri', 'Missouri'), ('Lower Central Valley', 'Lower Central Valley'), ('Atlanta / Athens', 'Atlanta / Athens'), ('Southern Jersey', 'Southern Jersey'), ('Idaho', 'Idaho'), ('LA Metro', 'LA Metro'), ('West Washington', 'West Washington'), ('Orange County', 'Orange County'), ('Oregon / SW Washington', 'Oregon / SW Washington'), ('Mississippi', 'Mississippi'), ('South Texas', 'South Texas'), ('San Antonio', 'San Antonio'), ('Milwaukee', 'Milwaukee'), ('Cincinnati', 'Cincinnati'), ('North Wisconsin', 'North Wisconsin'), ('Rochester', 'Rochester'), ('Houston', 'Houston'), ('Norfolk', 'Norfolk'), ('Miami / West Palm', 'Miami / West Palm'), ('Las Vegas', 'Las Vegas'), ('Cleveland', 'Cleveland'), ('East Michigan', 'East Michigan'), ('Chicago', 'Chicago'), ('SF Bay', 'SF Bay'), ('GA/SC Coast', 'GA/SC Coast'), ('Delaware', 'Delaware'), ('Phoenix', 'Phoenix'), ('West Iowa / Nebraska', 'West Iowa / Nebraska'), ('Pittsburgh', 'Pittsburgh'), ('Austin', 'Austin'), ('Tampa', 'Tampa'), ('Louisiana', 'Louisiana'), ('Gulf Coast', 'Gulf Coast'), ('Long Island', 'Long Island'), ('Charlotte', 'Charlotte'), ('Toledo', 'Toledo'), ('Minnesota', 'Minnesota'), ('Columbus', 'Columbus'), ('Philadelphia Metro', 'Philadelphia Metro'), ('Colorado', 'Colorado'), ('Oklahoma', 'Oklahoma'), ('Upper Central Valley', 'Upper Central Valley'), ('Ft. Wayne / South Bend', 'Ft. Wayne / South Bend'), ('Boston', 'Boston'), ('Raleigh / Durham', 'Raleigh / Durham'), ('Winston / Salem', 'Winston / Salem'), ('Arkansas', 'Arkansas'), ('San Diego', 'San Diego'), ('Myrtle Beach', 'Myrtle Beach'), ('Upstate NY East', 'Upstate NY East'), ('Central Illinois', 'Central Illinois'), ('Northern Jersey', 'Northern Jersey'), ('Central Pennsylvania', 'Central Pennsylvania'), ('The Panhandle', 'The Panhandle'), ('Providence', 'Providence'), ('Upstate NY Central', 'Upstate NY Central'), ('West Michigan', 'West Michigan'), ('Utah', 'Utah'), ('Tucson / Yuma', 'Tucson / Yuma'), ('New York City', 'New York City'), ('VT / NH / ME', 'VT / NH / ME'), ('Hawaii', 'Hawaii'), ('Northern Connecticut', 'Northern Connecticut'), ('Richmond', 'Richmond'), ('Western Pennsylvania', 'Western Pennsylvania'), ('Southern Virginia', 'Southern Virginia'), ('Memphis', 'Memphis'), ('Baltimore', 'Baltimore'), ('Southern Connecticut', 'Southern Connecticut'), ('Indianapolis', 'Indianapolis'), ('New Orleans', 'New Orleans'), ('Buffalo', 'Buffalo'), ('South West Florida', 'South West Florida'), ('North LA', 'North LA'), ('South Bay', 'South Bay'), ('West Virginia', 'West Virginia')], max_length=255)),
                ('eNB', models.CharField(blank=True, default='', max_length=255)),
                ('CSMS', models.CharField(blank=True, default='', max_length=255)),
                ('OSS', models.CharField(blank=True, default='', max_length=255)),
                ('Ageing', models.IntegerField(blank=True, default=0)),
                ('Alarm_Status', models.CharField(blank=True, default='', max_length=255)),
                ('Nims', models.CharField(blank=True, default='', max_length=255)),
                ('ACD', models.CharField(blank=True, default='', max_length=255)),
                ('TVW', models.CharField(blank=True, default='', max_length=255)),
                ('PRTS', models.CharField(blank=True, default='', max_length=255)),
                ('Patrol', models.CharField(blank=True, default='', max_length=255)),
                ('Trams', models.CharField(blank=True, default='', max_length=255)),
                ('NEO', models.CharField(blank=True, default='', max_length=255)),
                ('Category', models.CharField(blank=True, default='', max_length=255)),
                ('Owner', models.CharField(blank=True, default='', max_length=255)),
                ('Volte_Soft_Launch_Status', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255)),
                ('OAR_Date', models.DateField(blank=True, null=True)),
                ('OAC_Date', models.DateField(blank=True, null=True)),
                ('Initail_Status', models.CharField(blank=True, default='', max_length=255)),
                ('Final_Status', models.CharField(blank=True, default='', max_length=255)),
                ('CICO', models.CharField(blank=True, default='', max_length=255)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Date', models.DateField(blank=True, null=True)),
                ('Assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alursaprofile', to='alu.AluProfile')),
                ('admin', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alursacounts', to='alu.ALUCounts')),
            ],
        ),
    ]
