# Generated by Django 2.0.13 on 2019-05-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alu', '0007_alursatracker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alursatracker',
            old_name='Initail_Status',
            new_name='Initial_Status',
        ),
        migrations.RenameField(
            model_name='alursatracker',
            old_name='Sity_Type',
            new_name='Site_Type',
        ),
        migrations.AddField(
            model_name='alursatracker',
            name='Remark',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='alursatracker',
            name='SV_3115',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='alursatracker',
            name='CICO',
            field=models.CharField(blank=True, choices=[('Fail', 'Pass'), ('Fail', 'Pass')], max_length=255),
        ),
        migrations.AlterField(
            model_name='alursatracker',
            name='OAC_Date',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alursatracker',
            name='OAR_Date',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=255),
            preserve_default=False,
        ),
    ]
