# Generated by Django 2.0.13 on 2019-05-14 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alu', '0008_auto_20190515_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alursatracker',
            name='CICO',
            field=models.CharField(blank=True, choices=[('Fail', 'Fail'), ('Pass', 'Pass')], max_length=255),
        ),
    ]
