# Generated by Django 2.0.13 on 2019-05-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ericsson', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ericssonpostcomtracker',
            old_name='Alarms_Preventing_RET_Config',
            new_name='CIC_Airboss_Mail',
        ),
        migrations.RenameField(
            model_name='ericssonpostcomtracker',
            old_name='IP_Route_or_IP_Address',
            new_name='Construction_Manager_Mail',
        ),
        migrations.RenameField(
            model_name='ericssonpostcomtracker',
            old_name='LSM',
            new_name='ENM',
        ),
        migrations.RenameField(
            model_name='ericssonpostcomtracker',
            old_name='Lock_Unlock_Verified_By',
            new_name='IP_OAM',
        ),
        migrations.RenameField(
            model_name='ericssonpostcomtracker',
            old_name='Review_LATP_Complete',
            new_name='RSD_Airboss_Mail',
        ),
        migrations.RenameField(
            model_name='ericssonpostcomtracker',
            old_name='Verify_Status',
            new_name='RSD_Manager_Mail',
        ),
        migrations.RenameField(
            model_name='ericssonpostcomtracker',
            old_name='E_Link_Status_of_BH0_for_CDU30',
            new_name='Secondary_Fibre_check',
        ),
        migrations.RenameField(
            model_name='ericssonpostcomtracker',
            old_name='Volte_MME_IP_Config',
            new_name='Tech_Contact',
        ),
        migrations.RemoveField(
            model_name='ericssonpostcomtracker',
            name='Bandwidth_Checked_From_LSM',
        ),
        migrations.RemoveField(
            model_name='ericssonpostcomtracker',
            name='Frequency_Earfcn_Checked_from_LSM_BSM',
        ),
        migrations.RemoveField(
            model_name='ericssonpostcomtracker',
            name='MJ_Object_Marked',
        ),
        migrations.RemoveField(
            model_name='ericssonpostcomtracker',
            name='Mode_of_Communication',
        ),
        migrations.RemoveField(
            model_name='ericssonpostcomtracker',
            name='RET',
        ),
        migrations.RemoveField(
            model_name='ericssonpostcomtracker',
            name='Type',
        ),
        migrations.AddField(
            model_name='ericssonpostcomtracker',
            name='Kpi_Profile',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ericssonpostcomtracker',
            name='Revisit',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('NA', 'NA')], max_length=255),
        ),
        migrations.AddField(
            model_name='ericssonpostcomtracker',
            name='Revisit_Required',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('NA', 'NA')], max_length=255),
        ),
        migrations.AddField(
            model_name='ericssonpostcomtracker',
            name='Site_Post_Status',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ericssonpostcomtracker',
            name='Site_Pre_Status',
            field=models.CharField(blank=True, choices=[('On', 'On'), ('OFF', 'OFF'), ('NA', 'NA')], max_length=255),
        ),
        migrations.AddField(
            model_name='ericssonpostcomtracker',
            name='Tech_Email',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='ericssonpostcomtracker',
            name='Technology',
            field=models.CharField(choices=[('800 FDD', '800 FDD'), ('1900 FDD', '1900 FDD'), ('2.5 TDD', '2.5 TDD'), ('1900 800 FDD', '1900/800 FDD')], max_length=255),
        ),
    ]
