# Generated by Django 2.0.13 on 2019-05-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ericsson', '0002_auto_20190509_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ericssonpostcomtracker',
            name='Technology',
            field=models.CharField(choices=[('800 FDD', '800 FDD'), ('1900 FDD', '1900 FDD'), ('2.5 TDD', '2.5 TDD'), ('1900 800 FDD', '1900/800 FDD'), ('1900 CDMA', '1900 CDMA'), ('800 CDMA', '800 CDMA'), ('800/1900 CDMA', '800/1900 CDMA')], max_length=255),
        ),
    ]
