# Generated by Django 2.0.13 on 2019-05-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ericsson', '0003_auto_20190515_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ericssonpostcomtracker',
            name='Activity_status',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('Pending', 'Pending')], max_length=255),
        ),
        migrations.AlterField(
            model_name='ericssonpostcomtracker',
            name='Secondary_Fibre_check',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('Pending', 'Pending')], max_length=255),
        ),
    ]
