# Generated by Django 2.0.13 on 2019-05-20 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ericsson', '0005_auto_20190520_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ericsson_Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EricssonProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ericssonpostcomtracker',
            name='Assignee',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='ericssonprofile', to='ericsson.EricssonProfile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ericssonpostcomtracker',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ericssoncounts', to='ericsson.Ericsson_Count'),
        ),
    ]
