# Generated by Django 2.0.13 on 2019-05-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ericsson', '0008_auto_20190523_2323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ericssonrsatracker',
            old_name='Latest_Software',
            new_name='Latest_Software_Version',
        ),
        migrations.RenameField(
            model_name='ericssonrsatracker',
            old_name='RSA_Holdup_Reason',
            new_name='RSA_Hold_Reason',
        ),
        migrations.RenameField(
            model_name='ericssonrsatracker',
            old_name='Site_Unlock',
            new_name='Site_Unlock_Status',
        ),
        migrations.RenameField(
            model_name='ericssonrsatracker',
            old_name='Volte_Soft',
            new_name='Volte_Soft_Launch',
        ),
        migrations.AddField(
            model_name='ericssonrsatracker',
            name='Remark',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
