# Generated by Django 2.1.4 on 2019-01-16 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0002_auto_20190111_2006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracker',
            old_name='text1',
            new_name='Activity_status',
        ),
        migrations.RenameField(
            model_name='tracker',
            old_name='text2',
            new_name='Bandwidth_Checked_From_LSM',
        ),
        migrations.RenameField(
            model_name='tracker',
            old_name='text3',
            new_name='CSMS',
        ),
        migrations.AddField(
            model_name='tracker',
            name='Cic_Engineer',
            field=models.CharField(default='SOME STRING', max_length=500),
        ),
        migrations.AddField(
            model_name='tracker',
            name='FE_Name',
            field=models.CharField(default='SOME STRING', max_length=500),
        ),
        migrations.AddField(
            model_name='tracker',
            name='LSM',
            field=models.CharField(default='SOME STRING', max_length=500),
        ),
        migrations.AddField(
            model_name='tracker',
            name='Market',
            field=models.CharField(default='SOME STRING', max_length=500),
        ),
        migrations.AddField(
            model_name='tracker',
            name='Mode_of_Communication',
            field=models.CharField(default='SOME STRING', max_length=500),
        ),
        migrations.AddField(
            model_name='tracker',
            name='Site_Status_post_Activity',
            field=models.CharField(default='SOME STRING', max_length=500),
        ),
        migrations.AddField(
            model_name='tracker',
            name='Site_Status_pre_Activity',
            field=models.CharField(default='SOME STRING', max_length=500),
        ),
        migrations.AddField(
            model_name='tracker',
            name='Technology',
            field=models.CharField(default='SOME STRING', max_length=500),
        ),
        migrations.AddField(
            model_name='tracker',
            name='Type',
            field=models.CharField(default='SOME STRING', max_length=500),
        ),
        migrations.AddField(
            model_name='tracker',
            name='cascade',
            field=models.CharField(default='SOME STRING', max_length=500),
        ),
        migrations.AddField(
            model_name='tracker',
            name='eNB',
            field=models.CharField(default='SOME STRING', max_length=500),
        ),
    ]
