# Generated by Django 2.1.4 on 2019-01-22 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0003_auto_20190116_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='days',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='days', max_length=1),
            preserve_default=False,
        ),
    ]
