# Generated by Django 2.1.4 on 2019-01-22 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0004_tracker_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='days',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
