# Generated by Django 2.1.4 on 2019-02-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0005_auto_20190122_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracker',
            name='days',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='title',
        ),
        migrations.AddField(
            model_name='tracker',
            name='Activity',
            field=models.CharField(choices=[('1', 'C&I'), ('2', 'Troubleshoot'), ('3', 'LATP Testing'), ('4', 'FATP Testing'), ('5', 'Pre-Integration'), ('6', 'Update to FE'), ('7', 'C&I Task in Appian'), ('8', 'Review LATP in Appian')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='tracker',
            name='Alarms_Preventing_RET_Config',
            field=models.CharField(blank=True, default='SOME STRING', max_length=500),
        ),
        migrations.AddField(
            model_name='tracker',
            name='E_Link_Status_of_BH0_for_CDU30',
            field=models.CharField(blank=True, choices=[('1', 'On'), ('2', 'OFF'), ('3', 'NA')], max_length=1),
        ),
        migrations.AddField(
            model_name='tracker',
            name='Final_Comments',
            field=models.CharField(blank=True, default='SOME STRING', max_length=500),
        ),
        migrations.AddField(
            model_name='tracker',
            name='Frequency_Earfcn_Checked_from_LSM_BSM',
            field=models.CharField(blank=True, choices=[('1', 'Yes'), ('2', 'No'), ('2', 'Not Required')], max_length=1),
        ),
        migrations.AddField(
            model_name='tracker',
            name='IP_Route_or_IP_Address',
            field=models.CharField(blank=True, default='SOME STRING', max_length=500),
        ),
        migrations.AddField(
            model_name='tracker',
            name='Lock_Unlock_Verified_By',
            field=models.CharField(blank=True, default='SOME STRING', max_length=500),
        ),
        migrations.AddField(
            model_name='tracker',
            name='MJ_Object_Marked',
            field=models.CharField(blank=True, choices=[('1', 'Marked'), ('2', 'Not Marked'), ('3', 'NA')], max_length=1),
        ),
        migrations.AddField(
            model_name='tracker',
            name='OAC_Date',
            field=models.CharField(default='SOME STRING', max_length=500),
        ),
        migrations.AddField(
            model_name='tracker',
            name='OAR_Date',
            field=models.CharField(default='SOME STRING', max_length=500),
        ),
        migrations.AddField(
            model_name='tracker',
            name='RET',
            field=models.CharField(blank=True, choices=[('1', 'Defined/Matched'), ('2', 'Defined/NotMached'), ('3', 'Not Define'), ('4', 'NA')], max_length=1),
        ),
        migrations.AddField(
            model_name='tracker',
            name='Remarks',
            field=models.CharField(blank=True, default='SOME STRING', max_length=500),
        ),
        migrations.AddField(
            model_name='tracker',
            name='Review_LATP_Complete',
            field=models.CharField(blank=True, default='SOME STRING', max_length=500),
        ),
        migrations.AddField(
            model_name='tracker',
            name='Verify_Status',
            field=models.CharField(blank=True, default='SOME STRING', max_length=500),
        ),
        migrations.AddField(
            model_name='tracker',
            name='Volte_MME_IP_Config',
            field=models.CharField(blank=True, default='SOME STRING', max_length=500),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='Activity_status',
            field=models.CharField(choices=[('1', 'Open'), ('2', 'Close'), ('3', 'Handover')], max_length=1),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='Bandwidth_Checked_From_LSM',
            field=models.CharField(choices=[('1', '3Mhz'), ('2', '5Mhz'), ('3', '10Mhz'), ('4', '20Mhz'), ('5', '5+10Mhz/5Mhz'), ('6', '5+10Mhz/3Mhz'), ('7', '10+5Mhz/5Mhz'), ('8', '10+5Mhz/3Mhz'), ('9', 'NA')], max_length=1),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='CSMS',
            field=models.CharField(default='CSMS', max_length=500),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='Cic_Engineer',
            field=models.CharField(choices=[('1', 'Amit Yadav M'), ('2', 'Sankalita Banerjee'), ('3', 'Gurpreet Yadav'), ('4', 'Pradipta Mukherjee'), ('5', 'Abhishek Kumar DD'), ('6', 'Susheel'), ('7', 'P Rama Krishna'), ('8', 'Anand chowdhary'), ('9', 'Tarunam Mahajan'), ('10', 'Prem Prakash Rai'), ('11', 'Pravesh Kumar'), ('12', 'Shyam Singh Chauhan'), ('13', 'Vaibhav Bhatt')], max_length=1),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='FE_Name',
            field=models.CharField(default='FE_Name', max_length=500),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='LSM',
            field=models.CharField(default='LSM', max_length=500),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='Market',
            field=models.CharField(default='Market', max_length=500),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='Mode_of_Communication',
            field=models.CharField(choices=[('1', 'Whatsapp'), ('2', 'Primary Bridge'), ('3', 'Secondary Bridge'), ('4', 'IM'), ('5', 'E-Mail')], max_length=1),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='Site_Status_post_Activity',
            field=models.CharField(blank=True, default='Site_Status', max_length=500),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='Site_Status_pre_Activity',
            field=models.CharField(choices=[('1', 'Lock'), ('2', 'Unlock'), ('3', 'N/A')], max_length=1),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='Technology',
            field=models.CharField(choices=[('1', '800 CDMA'), ('2', '1900 CDMA'), ('3', '800 FDD'), ('4', '1900 FDD'), ('5', '2.5 TDD'), ('6', '1900/800 CDMA'), ('7', '1900/800 FDD'), ('8', '1900/700 FDD'), ('9', '1900/700 CDMA'), ('10', '700 FDD'), ('11', '700 CDMA'), ('12', '800 FDD/CDMA'), ('13', '700 FDD/CDMA')], max_length=1),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='Type',
            field=models.CharField(choices=[('1', 'Whatsapp'), ('2', 'Primary Bridge'), ('3', 'Secondary Bridge'), ('4', 'IM'), ('5', 'E-Mail')], max_length=1),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='cascade',
            field=models.CharField(default='Cascade', max_length=500),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='eNB',
            field=models.CharField(default='eNB', max_length=500),
        ),
    ]
