# Generated by Django 2.1.4 on 2019-02-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0006_auto_20190203_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='Activity',
            field=models.CharField(choices=[('1', 'C&I'), ('2', 'Troubleshoot'), ('3', 'LATP Testing'), ('4', 'FATP Testing'), ('5', 'Pre-Integration'), ('6', 'Update to FE'), ('7', 'C&I Task in Appian'), ('8', 'Review LATP in Appian')], max_length=1),
        ),
    ]
