# Generated by Django 2.1.4 on 2019-02-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0007_auto_20190203_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='Final_Comments',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='IP_Route_or_IP_Address',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='Lock_Unlock_Verified_By',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='OAC_Date',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='OAR_Date',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='Remarks',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='Review_LATP_Complete',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='Type',
            field=models.CharField(choices=[('1', 'CDU10'), ('2', 'CDU20'), ('3', 'CDU30'), ('4', 'NA')], max_length=1),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='Verify_Status',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='Volte_MME_IP_Config',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='cascade',
            field=models.CharField(default='', max_length=500),
        ),
    ]
