# Generated by Django 2.1.4 on 2019-02-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0008_auto_20190203_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='CSMS',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='FE_Name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='LSM',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='Market',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='Site_Status_post_Activity',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='eNB',
            field=models.CharField(default='', max_length=500),
        ),
    ]
