# Generated by Django 2.1.4 on 2019-02-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0009_auto_20190203_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='Technology',
            field=models.CharField(choices=[('800 CDMA', '800 CDMA'), ('1900 CDMA', '1900 CDMA'), ('800 FDD', '800 FDD'), ('1900 FDD', '1900 FDD'), ('2.5 TDD', '2.5 TDD'), ('1900/800 CDMA', '1900/800 CDMA'), ('1900/800 FDD', '1900/800 FDD'), ('1900/700 CDMA', '1900/700 CDMA'), ('700 CDMA', '700 CDMA'), ('800 FDD/CDMA', '800 FDD/CDMA')], max_length=1),
        ),
    ]
