# Generated by Django 2.1.4 on 2019-02-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0011_auto_20190207_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracker',
            name='Cic_Engineer',
        ),
        migrations.AlterField(
            model_name='tracker',
            name='Activity',
            field=models.CharField(choices=[('C&I', 'C&I'), ('Troubleshoot', 'Troubleshoot'), ('LATP Testing', 'LATP Testing'), ('FATP Testing', 'FATP Testing'), ('Pre-Integration', 'Pre-Integration'), ('Update to FE', 'Update to FE'), ('C&I Task in Appian', 'C&I Task in Appian'), ('Review LATP in Appian', 'Review LATP in Appian')], max_length=255),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='Activity_status',
            field=models.CharField(choices=[('Open', 'Open'), ('Close', 'Close'), ('Handover', 'Handover')], max_length=255),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='Alarms_Preventing_RET_Config',
            field=models.CharField(blank=True, default='SOME STRING', max_length=255),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='Bandwidth_Checked_From_LSM',
            field=models.CharField(choices=[('3Mhz', '3Mhz'), ('5Mhz', '5Mhz'), ('10Mhz', '10Mhz'), ('20Mhz', '20Mhz'), ('5+10Mhz/5Mhz', '5+10Mhz/5Mhz'), ('5+10Mhz/3Mhz', '5+10Mhz/3Mhz'), ('10+5Mhz/5Mhz', '10+5Mhz/5Mhz'), ('10+5Mhz/3Mhz', '10+5Mhz/3Mhz'), ('NA', 'NA')], max_length=255),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='CSMS',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='E_Link_Status_of_BH0_for_CDU30',
            field=models.CharField(blank=True, choices=[('On', 'On'), ('OFF', 'OFF'), ('NA', 'NA')], max_length=255),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='FE_Name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='Frequency_Earfcn_Checked_from_LSM_BSM',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Not Required', 'Not Required')], max_length=255),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='LSM',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='MJ_Object_Marked',
            field=models.CharField(blank=True, choices=[('Marked', 'Marked'), ('Not Marked', 'Not Marked'), ('NA', 'NA')], max_length=255),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='Market',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='Mode_of_Communication',
            field=models.CharField(choices=[('Whatsapp', 'Whatsapp'), ('Primary Bridge', 'Primary Bridge'), ('Secondary Bridge', 'Secondary Bridge'), ('IM', 'IM'), ('E-Mail', 'E-Mail')], max_length=255),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='RET',
            field=models.CharField(blank=True, choices=[('Defined/Matched', 'Defined/Matched'), ('Defined/NotMatched', 'Defined/NotMatched'), ('Not Define', 'Not Define'), ('NA', 'NA')], max_length=255),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='Site_Status_post_Activity',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='Site_Status_pre_Activity',
            field=models.CharField(choices=[('Lock', 'Lock'), ('Unlock', 'Unlock'), ('N/A', 'N/A')], max_length=255),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='Technology',
            field=models.CharField(choices=[('800 CDMA', '800 CDMA'), ('1900 CDMA', '1900 CDMA'), ('800 FDD', '800 FDD'), ('1900 FDD', '1900 FDD'), ('2.5 TDD', '2.5 TDD'), ('1900/800 CDMA', '1900/800 CDMA'), ('1900/800 FDD', '1900/800 FDD'), ('1900/700 CDMA', '1900/700 CDMA'), ('700 CDMA', '700 CDMA'), ('800 FDD/CDMA', '800 FDD/CDMA')], max_length=255),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='Type',
            field=models.CharField(choices=[('CDU10', 'CDU10'), ('CDU20', 'CDU20'), ('CDU30', 'CDU30'), ('NA', 'NA')], max_length=255),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='cascade',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='eNB',
            field=models.CharField(default='', max_length=255),
        ),
    ]
