# Generated by Django 2.1.4 on 2019-02-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0013_auto_20190215_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='Final_Comments',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='Frequency_Earfcn_Checked_from_LSM_BSM',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Not Required', 'Not Required')], max_length=255),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='IP_Route_or_IP_Address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='Lock_Unlock_Verified_By',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='OAC_Date',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='OAR_Date',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='Remarks',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='Review_LATP_Complete',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='Verify_Status',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='Volte_MME_IP_Config',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
