# Generated by Django 2.1.4 on 2019-02-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0014_auto_20190215_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='Bandwidth_Checked_From_LSM',
            field=models.CharField(choices=[('3Mhz', '3Mhz'), ('5Mhz', '5Mhz'), ('10Mhz', '10Mhz'), ('20Mhz', '20Mhz'), ('5+10Mhz 5Mhz', '5+10Mhz/5Mhz'), ('5+10Mhz 3Mhz', '5+10Mhz/3Mhz'), ('10+5Mhz 5Mhz', '10+5Mhz/5Mhz'), ('10+5Mhz 3Mhz', '10+5Mhz/3Mhz'), ('NA', 'NA')], max_length=255),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='RET',
            field=models.CharField(blank=True, choices=[('Defined Matched', 'Defined/Matched'), ('Defined NotMatched', 'Defined/NotMatched'), ('Not Define', 'Not Define'), ('NA', 'NA')], max_length=255),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='Site_Status_pre_Activity',
            field=models.CharField(choices=[('Lock', 'Lock'), ('Unlock', 'Unlock'), ('NA', 'N/A')], max_length=255),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='Technology',
            field=models.CharField(choices=[('800 CDMA', '800 CDMA'), ('1900 CDMA', '1900 CDMA'), ('800 FDD', '800 FDD'), ('1900 FDD', '1900 FDD'), ('2.5 TDD', '2.5 TDD'), ('1900 800 CDMA', '1900/800 CDMA'), ('1900 800 FDD', '1900/800 FDD'), ('1900 700 CDMA', '1900/700 CDMA'), ('700 CDMA', '700 CDMA'), ('800 FDD CDMA', '800 FDD/CDMA')], max_length=255),
        ),
    ]
