# Generated by Django 2.1.4 on 2019-02-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0015_auto_20190216_0007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cascade1', models.CharField(default='', max_length=255)),
                ('cascade2', models.CharField(default='', max_length=255)),
                ('cascade3', models.CharField(default='', max_length=255)),
                ('cascade4', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
