# Generated by Django 2.1.4 on 2019-02-20 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0016_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracker',
            name='admin',
        ),
        migrations.DeleteModel(
            name='Tracker',
        ),
    ]
