# Generated by Django 2.1.4 on 2019-02-20 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Tracker', '0017_auto_20190221_0153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cascade', models.CharField(default='', max_length=255)),
                ('Technology', models.CharField(choices=[('800 CDMA', '800 CDMA'), ('1900 CDMA', '1900 CDMA'), ('800 FDD', '800 FDD'), ('1900 FDD', '1900 FDD'), ('2.5 TDD', '2.5 TDD'), ('1900 800 CDMA', '1900/800 CDMA'), ('1900 800 FDD', '1900/800 FDD'), ('1900 700 CDMA', '1900/700 CDMA'), ('700 CDMA', '700 CDMA'), ('800 FDD CDMA', '800 FDD/CDMA')], max_length=255)),
                ('Type', models.CharField(choices=[('CDU10', 'CDU10'), ('CDU20', 'CDU20'), ('CDU30', 'CDU30'), ('NA', 'NA')], max_length=255)),
                ('Bandwidth_Checked_From_LSM', models.CharField(choices=[('3Mhz', '3Mhz'), ('5Mhz', '5Mhz'), ('10Mhz', '10Mhz'), ('20Mhz', '20Mhz'), ('5+10Mhz 5Mhz', '5+10Mhz/5Mhz'), ('5+10Mhz 3Mhz', '5+10Mhz/3Mhz'), ('10+5Mhz 5Mhz', '10+5Mhz/5Mhz'), ('10+5Mhz 3Mhz', '10+5Mhz/3Mhz'), ('NA', 'NA')], max_length=255)),
                ('Market', models.CharField(default='', max_length=255)),
                ('eNB', models.CharField(default='', max_length=255)),
                ('LSM', models.CharField(default='', max_length=255)),
                ('CSMS', models.CharField(default='', max_length=255)),
                ('FE_Name', models.CharField(default='', max_length=255)),
                ('Mode_of_Communication', models.CharField(choices=[('Whatsapp', 'Whatsapp'), ('Primary Bridge', 'Primary Bridge'), ('Secondary Bridge', 'Secondary Bridge'), ('IM', 'IM'), ('E-Mail', 'E-Mail')], max_length=255)),
                ('Activity', models.CharField(choices=[('C&I', 'C&I'), ('Troubleshoot', 'Troubleshoot'), ('LATP Testing', 'LATP Testing'), ('FATP Testing', 'FATP Testing'), ('Pre-Integration', 'Pre-Integration'), ('Update to FE', 'Update to FE'), ('C&I Task in Appian', 'C&I Task in Appian'), ('Review LATP in Appian', 'Review LATP in Appian')], max_length=255)),
                ('Activity_status', models.CharField(choices=[('Open', 'Open'), ('Close', 'Close'), ('Handover', 'Handover')], max_length=255)),
                ('Site_Status_pre_Activity', models.CharField(choices=[('Lock', 'Lock'), ('Unlock', 'Unlock'), ('NA', 'N/A')], max_length=255)),
                ('Site_Status_post_Activity', models.CharField(blank=True, default='', max_length=255)),
                ('E_Link_Status_of_BH0_for_CDU30', models.CharField(blank=True, choices=[('On', 'On'), ('OFF', 'OFF'), ('NA', 'NA')], max_length=255)),
                ('MJ_Object_Marked', models.CharField(blank=True, choices=[('Marked', 'Marked'), ('Not Marked', 'Not Marked'), ('NA', 'NA')], max_length=255)),
                ('RET', models.CharField(blank=True, choices=[('Defined Matched', 'Defined/Matched'), ('Defined NotMatched', 'Defined/NotMatched'), ('Not Define', 'Not Define'), ('NA', 'NA')], max_length=255)),
                ('Alarms_Preventing_RET_Config', models.CharField(blank=True, default='SOME STRING', max_length=255)),
                ('Frequency_Earfcn_Checked_from_LSM_BSM', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Not Required', 'Not Required')], max_length=255)),
                ('IP_Route_or_IP_Address', models.CharField(blank=True, default='', max_length=255)),
                ('Volte_MME_IP_Config', models.CharField(blank=True, default='', max_length=255)),
                ('Review_LATP_Complete', models.CharField(blank=True, default='', max_length=255)),
                ('Remarks', models.CharField(blank=True, default='', max_length=255)),
                ('OAR_Date', models.CharField(default='', max_length=255)),
                ('OAC_Date', models.CharField(default='', max_length=255)),
                ('Lock_Unlock_Verified_By', models.CharField(blank=True, default='', max_length=255)),
                ('Verify_Status', models.CharField(blank=True, default='', max_length=255)),
                ('Final_Comments', models.CharField(blank=True, default='', max_length=255)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
