# Generated by Django 2.0.13 on 2019-02-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0018_tracker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='cascade1',
            new_name='User_Name',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='cascade2',
            new_name='cascade',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='cascade3',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='cascade4',
        ),
        migrations.AddField(
            model_name='assignment',
            name='Technology',
            field=models.CharField(choices=[('800 CDMA', '800 CDMA'), ('1900 CDMA', '1900 CDMA'), ('800 FDD', '800 FDD'), ('1900 FDD', '1900 FDD'), ('2.5 TDD', '2.5 TDD'), ('1900 800 CDMA', '1900/800 CDMA'), ('1900 800 FDD', '1900/800 FDD'), ('1900 700 CDMA', '1900/700 CDMA'), ('700 CDMA', '700 CDMA'), ('800 FDD CDMA', '800 FDD/CDMA')], default='2.5 TDD', max_length=255),
        ),
        migrations.AddField(
            model_name='assignment',
            name='Type',
            field=models.CharField(choices=[('CDU10', 'CDU10'), ('CDU20', 'CDU20'), ('CDU30', 'CDU30'), ('NA', 'NA')], default='CDU30', max_length=255),
        ),
    ]
