# Generated by Django 2.0.13 on 2019-02-22 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0021_auto_20190221_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracker',
            old_name='published_date',
            new_name='Date',
        ),
        migrations.AlterField(
            model_name='tracker',
            name='Activity',
            field=models.CharField(choices=[('C&I', 'C&I'), ('Troubleshoot', 'Troubleshoot'), ('LATP Testing', 'LATP Testing'), ('FATP Testing', 'FATP Testing'), ('Pre-Integration', 'Pre-Integration'), ('Update to FE', 'Update to FE')], max_length=255),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='Alarms_Preventing_RET_Config',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='Site_Status_post_Activity',
            field=models.CharField(blank=True, choices=[('Lock', 'Lock'), ('Unlock', 'Unlock'), ('NA', 'N/A')], max_length=255),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='Technology',
            field=models.CharField(choices=[('800 CDMA', '800 CDMA'), ('1900 CDMA', '1900 CDMA'), ('800 FDD', '800 FDD'), ('1900 FDD', '1900 FDD'), ('2.5 TDD', '2.5 TDD'), ('1900 800 CDMA', '1900/800 CDMA'), ('1900 800 FDD', '1900/800 FDD'), ('1900 700 CDMA', '1900/700 CDMA'), ('700 FDD', '700 FDD'), ('800 FDD CDMA', '800 FDD/CDMA')], max_length=255),
        ),
    ]
