# Generated by Django 2.0.13 on 2019-03-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0026_auto_20190301_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='level',
            field=models.SmallIntegerField(default=0),
        ),
    ]
