# Generated by Django 2.0.13 on 2019-03-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0027_assignment_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping', models.BooleanField()),
                ('shipping_destination', models.CharField(blank=True, choices=[('residential', 'Residential'), ('commercial', 'Commercial')], max_length=15)),
            ],
        ),
    ]
