# Generated by Django 2.0.13 on 2019-03-06 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0030_usermoduleprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermoduleprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserModuleProfile',
        ),
    ]
