# Generated by Django 2.0.13 on 2019-03-12 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0031_auto_20190307_0201'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingInfo',
        ),
    ]
