# Generated by Django 2.0.13 on 2019-03-12 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0033_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
