# Generated by Django 2.0.13 on 2019-03-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0034_delete_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='User_Name',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='level',
        ),
        migrations.AlterField(
            model_name='tracker',
            name='Market',
            field=models.CharField(choices=[('Kansas', 'Kansas'), ('Alaska', 'Alaska'), ('PR / VI', 'PR / VI'), ('DFW', 'DFW'), ('East Texas', 'East Texas'), ('Inland Northwest', 'Inland Northwest'), ('Albuquerque', 'Albuquerque'), ('Jacksonville', 'Jacksonville'), ('Nashville', 'Nashville'), ('West Texas', 'West Texas'), ('Washington DC', 'Washington DC'), ('East Iowa', 'East Iowa'), ('MT / WY', 'MT / WY'), ('South Carolina', 'South Carolina'), ('Riverside / San Bernardino', 'Riverside / San Bernardino'), ('East Kentucky', 'East Kentucky'), ('Alabama', 'Alabama'), ('West Kentucky', 'West Kentucky'), ('Dakotas', 'Dakotas'), ('Orlando', 'Orlando'), ('Central Iowa', 'Central Iowa'), ('Georgia', 'Georgia'), ('Missouri', 'Missouri'), ('Lower Central Valley', 'Lower Central Valley'), ('Atlanta / Athens', 'Atlanta / Athens'), ('Southern Jersey', 'Southern Jersey'), ('Idaho', 'Idaho'), ('LA Metro', 'LA Metro'), ('West Washington', 'West Washington'), ('Orange County', 'Orange County'), ('Oregon / SW Washington', 'Oregon / SW Washington'), ('Mississippi', 'Mississippi'), ('South Texas', 'South Texas'), ('San Antonio', 'San Antonio'), ('Milwaukee', 'Milwaukee'), ('Cincinnati', 'Cincinnati'), ('North Wisconsin', 'North Wisconsin'), ('Rochester', 'Rochester'), ('Houston', 'Houston'), ('Norfolk', 'Norfolk'), ('Miami / West Palm', 'Miami / West Palm'), ('Las Vegas', 'Las Vegas'), ('Cleveland', 'Cleveland'), ('East Michigan', 'East Michigan'), ('Chicago', 'Chicago'), ('SF Bay', 'SF Bay'), ('GA/SC Coast', 'GA/SC Coast'), ('Delaware', 'Delaware'), ('Phoenix', 'Phoenix'), ('West Iowa / Nebraska', 'West Iowa / Nebraska'), ('Pittsburgh', 'Pittsburgh'), ('Austin', 'Austin'), ('Tampa', 'Tampa'), ('Louisiana', 'Louisiana'), ('Gulf Coast', 'Gulf Coast'), ('Long Island', 'Long Island'), ('Charlotte', 'Charlotte'), ('Toledo', 'Toledo'), ('Minnesota', 'Minnesota'), ('Columbus', 'Columbus'), ('Philadelphia Metro', 'Philadelphia Metro'), ('Colorado', 'Colorado'), ('Oklahoma', 'Oklahoma'), ('Upper Central Valley', 'Upper Central Valley'), ('Ft. Wayne / South Bend', 'Ft. Wayne / South Bend'), ('Boston', 'Boston'), ('Raleigh / Durham', 'Raleigh / Durham'), ('Winston / Salem', 'Winston / Salem'), ('Arkansas', 'Arkansas'), ('San Diego', 'San Diego'), ('Myrtle Beach', 'Myrtle Beach'), ('Upstate NY East', 'Upstate NY East'), ('Central Illinois', 'Central Illinois'), ('Northern Jersey', 'Northern Jersey'), ('Central Pennsylvania', 'Central Pennsylvania'), ('The Panhandle', 'The Panhandle'), ('Providence', 'Providence'), ('Upstate NY Central', 'Upstate NY Central'), ('West Michigan', 'West Michigan'), ('Utah', 'Utah'), ('Tucson / Yuma', 'Tucson / Yuma'), ('New York City', 'New York City'), ('VT / NH / ME', 'VT / NH / ME'), ('Hawaii', 'Hawaii'), ('Northern Connecticut', 'Northern Connecticut'), ('Richmond', 'Richmond'), ('Western Pennsylvania', 'Western Pennsylvania'), ('Southern Virginia', 'Southern Virginia'), ('Memphis', 'Memphis'), ('Baltimore', 'Baltimore'), ('Southern Connecticut', 'Southern Connecticut'), ('Indianapolis', 'Indianapolis'), ('New Orleans', 'New Orleans'), ('Buffalo', 'Buffalo'), ('South West Florida', 'South West Florida'), ('North LA', 'North LA'), ('South Bay', 'South Bay'), ('West Virginia', 'West Virginia')], max_length=255),
        ),
    ]
