# Generated by Django 2.0.13 on 2019-03-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0035_auto_20190329_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='User_Name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
