# Generated by Django 2.0.13 on 2019-04-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0036_assignment_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='Type',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='created_date',
            field=models.DateField(),
        ),
    ]
