# Generated by Django 2.0.13 on 2019-04-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0037_auto_20190401_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='OAC_Date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='OAR_Date',
            field=models.DateField(null=True),
        ),
    ]
