# Generated by Django 2.0.13 on 2019-04-03 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0039_rsatracker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rsatracker',
            old_name='Verify_Status',
            new_name='Verifier_Status',
        ),
    ]
