# Generated by Django 2.0.13 on 2019-04-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0040_auto_20190403_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsatracker',
            name='Verifier_Status',
            field=models.CharField(blank=True, choices=[('Lock', 'Lock'), ('Unlock', 'Unlock')], default='', max_length=255),
        ),
    ]
