# Generated by Django 2.0.13 on 2019-04-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0041_auto_20190403_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsatracker',
            name='Assignee',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='rsatracker',
            name='Acd_Status',
            field=models.CharField(choices=[('Task 3105 is Actualized', 'Task 3105 is Actualized'), ('ACD Accepted', 'ACD Accepted'), ('TVW Received from WEST', 'TVW Received from WEST'), ('Ready for drive test', 'Ready for drive test'), ('ACD Error', 'ACD Error'), ('ACD Rejected', 'ACD Rejected'), ('ACD Created', 'ACD Created'), ('ACD Sent', 'ACD Sent'), ('Blank', 'Blank'), ('Rural Roaming Site. ACD not required.', 'Rural Roaming Site. ACD not required.')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='rsatracker',
            name='RTRV_SON_SO_status',
            field=models.CharField(choices=[('\xa0121000;121000;66000;66000', '\xa0121000;121000;66000;66000'), ('121000;121000', '121000;121000'), ('66000;66000', '66000;66000'), ('NA', 'NA')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='rsatracker',
            name='TVW_Available',
            field=models.CharField(choices=[('TVW Available in SV', 'TVW Available in SV'), ('Yes', 'Yes'), ('No', 'No'), ('Yes but incomplete data', 'Yes but incomplete data')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='rsatracker',
            name='TVW_Available_FMCC_Database',
            field=models.CharField(choices=[('TVW Available in West Extract Database', 'TVW Available in West Extract Database'), ('Yes', 'Yes'), ('No', 'No'), ('Rural Roaming Site. TVW not required.', 'Rural Roaming Site. TVW not required.'), ('NA', 'NA')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='rsatracker',
            name='TVW_Related_Remarks',
            field=models.CharField(choices=[('TVW Related Remarks', 'TVW Related Remarks'), ('informational only, no action required', 'informational only, no action required'), ('send completed ACD/TVW to West', 'send completed ACD/TVW to West'), ('Upload Complete TVW file to SV', 'Upload Complete TVW file to SV')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='rsatracker',
            name='Ticket_Raised_For_Issue',
            field=models.CharField(choices=[('PRTS', 'PRTS'), ('TRAMS', 'TRAMS'), ('NIMS', 'NIMS'), ('NEO', 'NEO'), ('PATROL', 'PATROL')], default='', max_length=255),
        ),
    ]
