# Generated by Django 2.0.13 on 2019-04-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0044_auto_20190404_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='Activity',
            field=models.CharField(blank=True, choices=[('C&I', 'C&I'), ('Troubleshoot', 'Troubleshoot'), ('LATP Testing', 'LATP Testing'), ('FATP Testing', 'FATP Testing'), ('Pre-Integration', 'Pre-Integration'), ('Update to FE', 'Update to FE')], max_length=255),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='Activity_status',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('Close', 'Close'), ('Handover', 'Handover')], max_length=255),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='Bandwidth_Checked_From_LSM',
            field=models.CharField(blank=True, choices=[('3Mhz', '3Mhz'), ('5Mhz', '5Mhz'), ('10Mhz', '10Mhz'), ('20Mhz', '20Mhz'), ('5+10Mhz 5Mhz', '5+10Mhz/5Mhz'), ('5+10Mhz 3Mhz', '5+10Mhz/3Mhz'), ('10+5Mhz 5Mhz', '10+5Mhz/5Mhz'), ('10+5Mhz 3Mhz', '10+5Mhz/3Mhz'), ('NA', 'NA')], max_length=255),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='CSMS',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='FE_Name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='LSM',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='Market',
            field=models.CharField(blank=True, choices=[('Kansas', 'Kansas'), ('Alaska', 'Alaska'), ('PR / VI', 'PR / VI'), ('DFW', 'DFW'), ('East Texas', 'East Texas'), ('Inland Northwest', 'Inland Northwest'), ('Albuquerque', 'Albuquerque'), ('Jacksonville', 'Jacksonville'), ('Nashville', 'Nashville'), ('West Texas', 'West Texas'), ('Washington DC', 'Washington DC'), ('East Iowa', 'East Iowa'), ('MT / WY', 'MT / WY'), ('South Carolina', 'South Carolina'), ('Riverside / San Bernardino', 'Riverside / San Bernardino'), ('East Kentucky', 'East Kentucky'), ('Alabama', 'Alabama'), ('West Kentucky', 'West Kentucky'), ('Dakotas', 'Dakotas'), ('Orlando', 'Orlando'), ('Central Iowa', 'Central Iowa'), ('Georgia', 'Georgia'), ('Missouri', 'Missouri'), ('Lower Central Valley', 'Lower Central Valley'), ('Atlanta / Athens', 'Atlanta / Athens'), ('Southern Jersey', 'Southern Jersey'), ('Idaho', 'Idaho'), ('LA Metro', 'LA Metro'), ('West Washington', 'West Washington'), ('Orange County', 'Orange County'), ('Oregon / SW Washington', 'Oregon / SW Washington'), ('Mississippi', 'Mississippi'), ('South Texas', 'South Texas'), ('San Antonio', 'San Antonio'), ('Milwaukee', 'Milwaukee'), ('Cincinnati', 'Cincinnati'), ('North Wisconsin', 'North Wisconsin'), ('Rochester', 'Rochester'), ('Houston', 'Houston'), ('Norfolk', 'Norfolk'), ('Miami / West Palm', 'Miami / West Palm'), ('Las Vegas', 'Las Vegas'), ('Cleveland', 'Cleveland'), ('East Michigan', 'East Michigan'), ('Chicago', 'Chicago'), ('SF Bay', 'SF Bay'), ('GA/SC Coast', 'GA/SC Coast'), ('Delaware', 'Delaware'), ('Phoenix', 'Phoenix'), ('West Iowa / Nebraska', 'West Iowa / Nebraska'), ('Pittsburgh', 'Pittsburgh'), ('Austin', 'Austin'), ('Tampa', 'Tampa'), ('Louisiana', 'Louisiana'), ('Gulf Coast', 'Gulf Coast'), ('Long Island', 'Long Island'), ('Charlotte', 'Charlotte'), ('Toledo', 'Toledo'), ('Minnesota', 'Minnesota'), ('Columbus', 'Columbus'), ('Philadelphia Metro', 'Philadelphia Metro'), ('Colorado', 'Colorado'), ('Oklahoma', 'Oklahoma'), ('Upper Central Valley', 'Upper Central Valley'), ('Ft. Wayne / South Bend', 'Ft. Wayne / South Bend'), ('Boston', 'Boston'), ('Raleigh / Durham', 'Raleigh / Durham'), ('Winston / Salem', 'Winston / Salem'), ('Arkansas', 'Arkansas'), ('San Diego', 'San Diego'), ('Myrtle Beach', 'Myrtle Beach'), ('Upstate NY East', 'Upstate NY East'), ('Central Illinois', 'Central Illinois'), ('Northern Jersey', 'Northern Jersey'), ('Central Pennsylvania', 'Central Pennsylvania'), ('The Panhandle', 'The Panhandle'), ('Providence', 'Providence'), ('Upstate NY Central', 'Upstate NY Central'), ('West Michigan', 'West Michigan'), ('Utah', 'Utah'), ('Tucson / Yuma', 'Tucson / Yuma'), ('New York City', 'New York City'), ('VT / NH / ME', 'VT / NH / ME'), ('Hawaii', 'Hawaii'), ('Northern Connecticut', 'Northern Connecticut'), ('Richmond', 'Richmond'), ('Western Pennsylvania', 'Western Pennsylvania'), ('Southern Virginia', 'Southern Virginia'), ('Memphis', 'Memphis'), ('Baltimore', 'Baltimore'), ('Southern Connecticut', 'Southern Connecticut'), ('Indianapolis', 'Indianapolis'), ('New Orleans', 'New Orleans'), ('Buffalo', 'Buffalo'), ('South West Florida', 'South West Florida'), ('North LA', 'North LA'), ('South Bay', 'South Bay'), ('West Virginia', 'West Virginia')], max_length=255),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='Mode_of_Communication',
            field=models.CharField(blank=True, choices=[('Whatsapp', 'Whatsapp'), ('Primary Bridge', 'Primary Bridge'), ('Secondary Bridge', 'Secondary Bridge'), ('IM', 'IM'), ('E-Mail', 'E-Mail')], max_length=255),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='OAC_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='OAR_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='Site_Status_pre_Activity',
            field=models.CharField(blank=True, choices=[('Lock', 'Lock'), ('Unlock', 'Unlock'), ('NA', 'N/A')], max_length=255),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='Technology',
            field=models.CharField(blank=True, choices=[('800 CDMA', '800 CDMA'), ('1900 CDMA', '1900 CDMA'), ('800 FDD', '800 FDD'), ('1900 FDD', '1900 FDD'), ('2.5 TDD', '2.5 TDD'), ('1900 800 CDMA', '1900/800 CDMA'), ('1900 800 FDD', '1900/800 FDD'), ('1900 700 CDMA', '1900/700 CDMA'), ('700 FDD', '700 FDD'), ('800 FDD CDMA', '800 FDD/CDMA')], max_length=255),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='Type',
            field=models.CharField(blank=True, choices=[('CDU10', 'CDU10'), ('CDU20', 'CDU20'), ('CDU30', 'CDU30'), ('NA', 'NA')], max_length=255),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='cascade',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='eNB',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
