# Generated by Django 2.0.13 on 2019-04-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0045_auto_20190405_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='Assignee',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
