# Generated by Django 2.0.13 on 2019-04-10 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0048_auto_20190405_0026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rsatracker',
            name='Activity',
        ),
        migrations.RemoveField(
            model_name='rsatracker',
            name='Activity_status',
        ),
        migrations.RemoveField(
            model_name='rsatracker',
            name='Verifier_Status',
        ),
    ]
