# Generated by Django 2.0.13 on 2019-04-11 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0049_auto_20190411_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsatracker',
            name='TVW_Available',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Yes but incomplete data', 'Yes but incomplete data')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='rsatracker',
            name='User_Name',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
