# Generated by Django 2.0.13 on 2019-04-12 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0050_auto_20190411_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsatracker',
            name='User_Name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
