# Generated by Django 2.0.13 on 2019-04-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0054_auto_20190413_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='Assignee',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
