# Generated by Django 2.0.13 on 2019-04-16 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0055_auto_20190413_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsatracker',
            name='Assignee',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='assignee1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rsatracker',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='Assignee',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='assignee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
