# Generated by Django 2.0.13 on 2019-04-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0057_auto_20190416_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsatracker',
            name='Assignee',
            field=models.CharField(max_length=255),
        ),
    ]
