# Generated by Django 2.0.13 on 2019-04-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0060_auto_20190416_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsatracker',
            name='Technology',
            field=models.CharField(choices=[('800 CDMA', '800 CDMA'), ('1900 CDMA', '1900 CDMA'), ('800 FDD', '800 FDD'), ('1900 FDD', '1900 FDD'), ('2.5 TDD', '2.5 TDD'), ('1900 800 CDMA', '1900/800 CDMA'), ('1900 800 FDD', '1900/800 FDD'), ('1900 700 CDMA', '1900/700 CDMA'), ('700 FDD', '700 FDD'), ('800 FDD CDMA', '800 FDD/CDMA')], max_length=255),
        ),
        migrations.AlterField(
            model_name='rsatracker',
            name='cascade',
            field=models.CharField(default='', max_length=255),
        ),
    ]
