# Generated by Django 2.0.13 on 2019-05-14 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0063_auto_20190514_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracker',
            name='Activity1',
        ),
    ]
