# Generated by Django 2.0.13 on 2019-05-14 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0064_remove_tracker_activity1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='activity',
        ),
    ]
