# Generated by Django 2.0.13 on 2019-05-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0065_delete_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='rsatracker',
            name='Bandwidth_Checked_From_LSM',
        ),
        migrations.AlterField(
            model_name='tracker',
            name='Activity',
            field=models.CharField(blank=True, choices=[('C&I', 'C&I'), ('Troubleshoot', 'Troubleshoot'), ('LATP Testing', 'LATP Testing'), ('FATP Testing', 'FATP Testing'), ('Pre-Integration', 'Pre-Integration'), ('Update to FE', 'Update to FE'), ('E911 Testing', 'E911 Testing'), ('LAM Testing', 'LAM Testing'), ('Grow with No Connectivity', 'Grow with No Connectivity'), ('Grow with Connectivity only', 'Grow with Connectivity only')], max_length=255),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='Bandwidth_Checked_From_LSM',
            field=models.CharField(blank=True, choices=[('3Mhz', '3Mhz'), ('5Mhz', '5Mhz'), ('10Mhz', '10Mhz'), ('15Mhz', '15Mhz'), ('20Mhz', '20Mhz'), ('5+10Mhz 5Mhz', '5+10Mhz/5Mhz'), ('5+10Mhz 3Mhz', '5+10Mhz/3Mhz'), ('10+5Mhz 5Mhz', '10+5Mhz/5Mhz'), ('10+5Mhz 3Mhz', '10+5Mhz/3Mhz'), ('5+5 Mhz/5 Mhz', '5+5 Mhz/5 Mhz'), ('5 Mhz/3 Mhz', '5 Mhz/3 Mhz'), ('5 Mhz/5 Mhz', '5 Mhz/5 Mhz'), ('10 Mhz/3 Mhz', '10 Mhz/3 Mhz'), ('10 Mhz/5 Mhz', '10 Mhz/5 Mhz'), ('15 Mhz/3 Mhz', '15 Mhz/3 Mhz'), ('15 Mhz/5 Mhz', '15 Mhz/5 Mhz'), ('5+5 Mhz/3 Mhz', '5+5 Mhz/3 Mhz'), ('NA', 'NA')], max_length=255),
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
    ]
