# Generated by Django 2.0.13 on 2019-05-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0066_auto_20190521_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='E_Link_Status_of_BH0_for_CDU30',
            field=models.CharField(blank=True, choices=[('On', 'On'), ('OFF', 'OFF'), ('NA', 'NA')], max_length=255, null=True),
        ),
    ]
