# Generated by Django 2.0.13 on 2019-05-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0067_auto_20190530_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='Frequency_Earfcn_Checked_from_LSM_BSM',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Not Required', 'Not Required')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='MJ_Object_Marked',
            field=models.CharField(blank=True, choices=[('Marked', 'Marked'), ('Not Marked', 'Not Marked'), ('NA', 'NA')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='RET',
            field=models.CharField(blank=True, choices=[('Defined Matched', 'Defined/Matched'), ('Defined NotMatched', 'Defined/NotMatched'), ('Not Define', 'Not Define'), ('NA', 'NA')], max_length=255, null=True),
        ),
    ]
