# Generated by Django 2.0.13 on 2019-05-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0068_auto_20190530_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='Site_Status_post_Activity',
            field=models.CharField(blank=True, choices=[('Lock', 'Lock'), ('Unlock', 'Unlock'), ('NA', 'N/A')], max_length=255, null=True),
        ),
    ]
